### ISSUE TITLE
Yup array validation for each field in an array

### ISSUE THREAD

**Issue by devevignesh** [formik/formik#2559]
## I want to validate each field in an array of objects. 

For example: I have 5 objects in an array "invitees". I want to validate only if inner constraints are satisfied

```
const validationSchema = Yup.object().shape({
  invitees: Yup.array().of(
    Yup.object().shape(
      {
        first_name: Yup.string().when(["email_id", "related_as"], {
          is: (email_id, related_as) => email_id || related_as,
          then: Yup.string().required("Enter first name"),
        }),
        email_id: Yup.string()
          .email("Enter a valid email")
          .when(["first_name", "related_as"], {
            is: (first_name, related_as) => first_name || related_as,
            then: Yup.string().required("Enter an email"),
          }),
        related_as: Yup.string().when(["first_name", "email_id"], {
          is: (first_name, email_id) => first_name || email_id,
          then: Yup.string().required("Select role"),
        }),
      },
      [
        ["first_name", "email_id"],
        ["first_name", "related_as"],
        ["email_id", "related_as"],
      ]
    )
  ),
});
```

**Comment by vipcxj** [comment]
我认为Yup不是一个用于一次性解决验证的工具。它根本不能应对复杂的情形，它甚至不支持有序地验证。很多时候与其花费大量的时间查询Yup可能做不到的事，不如在一个大的验证函数中，在需要的时候使用Yup验证单个值。
I don't think Yup is a good tool for solving validation once for all. It doesn't even support sequential validation.  Instead of spending a lot of time google for the things that Yup might not be able to do, it's better to use Yup in a large validation function to validate individual values as needed, then you have full control of the logical of validation.
